"""Phase 4: generates STDM-style tenure documentation -- one PDF
certificate per validated (non-disputed) social tenure relationship, the
actual FFP deliverable a household walks away with. This is what STDM's
own Document Generator module produces from its schema; here it's built
directly with reportlab from the stdm.gpkg tables, using the same
party/spatial_unit/STR data.

Only issued for validated STRs, one per tenure type plus a couple of
extras -- a representative sample, not all 416, to keep the repo lean.
Disputed STRs get no certificate; they're exactly the material Phase 5's
adjudication queue works from.

Run: python3 scripts/generate_certificates.py
Output: outputs/certificates/<str_id>.pdf
"""

import os
import sqlite3

import geopandas as gpd
import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..")
SYN_DIR = os.path.join(REPO_ROOT, "data", "synthetic")
GPKG_PATH = os.path.join(SYN_DIR, "stdm.gpkg")
PHOTOS_DIR = os.path.join(SYN_DIR, "field_photos")
OUT_DIR = os.path.join(REPO_ROOT, "outputs", "certificates")

TENURE_LABELS = {
    "owned_documented": "Owned, has documentation",
    "owned_undocumented": "Owned, no documentation",
    "rented": "Rented",
    "informal_occupation": "Informal occupation (no ownership claim)",
    "customary": "Customary / community-recognized claim",
}


def pick_sample(str_df):
    validated = str_df[str_df.str_status == "validated"]
    sample = validated.groupby("tenure_type_id", group_keys=False).head(1)
    extra = validated[~validated.str_id.isin(sample.str_id)].sample(n=3, random_state=5)
    return pd.concat([sample, extra]).sort_values("str_id")


def draw_certificate(path, str_row, party_row, spatial_row):
    c = canvas.Canvas(path, pagesize=A4)
    w, h = A4
    margin = 20 * mm

    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(w / 2, h - margin, "Certificate of Social Tenure")
    c.setFont("Helvetica", 10)
    c.drawCentredString(w / 2, h - margin - 16, "Fit-For-Purpose Land Administration Pilot")

    c.setFillColorRGB(0.75, 0.1, 0.1)
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(w / 2, h - margin - 34,
                         "SYNTHETIC DEMONSTRATION DOCUMENT -- NOT A LEGAL INSTRUMENT -- NO REAL PERSON OR PLACE")
    c.setFillColorRGB(0, 0, 0)

    y = h - margin - 60
    line_h = 16

    def field(label, value):
        nonlocal y
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin, y, label)
        c.setFont("Helvetica", 10)
        c.drawString(margin + 55 * mm, y, str(value))
        y -= line_h

    field("STR ID:", str_row.str_id)
    field("Claimant:", party_row.full_name)
    field("National ID (synthetic):", party_row.national_id)
    field("Household size:", int(party_row.household_size))
    field("Parcel ID:", spatial_row.spatial_unit_id)
    field("Parcel area:", f"{spatial_row.area_m2:.1f} m2")
    field("Tenure type:", TENURE_LABELS.get(str_row.tenure_type_id, str_row.tenure_type_id))
    field("Status:", str_row.str_status)
    field("Validity start:", str_row.validity_start)
    field("Documented by:", str_row.documented_by if isinstance(str_row.documented_by, str) else "(no photo captured)")

    y -= 10
    photo_path = os.path.join(PHOTOS_DIR, str_row.documented_by) if isinstance(str_row.documented_by, str) else None
    if photo_path and os.path.exists(photo_path):
        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin, y, "Parcel evidence photo:")
        y -= 4 * mm
        c.drawImage(photo_path, margin, y - 45 * mm, width=60 * mm, height=45 * mm, preserveAspectRatio=True)
        y -= 50 * mm

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(margin, margin, "Generated by scripts/generate_certificates.py from data/synthetic/stdm.gpkg -- see model/README.md and data/synthetic/README.md.")

    c.showPage()
    c.save()


def main():
    spatial_unit = gpd.read_file(GPKG_PATH, layer="spatial_unit")
    conn = sqlite3.connect(GPKG_PATH)
    party = pd.read_sql("SELECT * FROM party", conn)
    str_table = pd.read_sql("SELECT * FROM social_tenure_relationship", conn)
    conn.close()

    sample = pick_sample(str_table)
    os.makedirs(OUT_DIR, exist_ok=True)

    for _, str_row in sample.iterrows():
        party_row = party[party.party_id == str_row.party_id].iloc[0]
        spatial_row = spatial_unit[spatial_unit.spatial_unit_id == str_row.spatial_unit_id].iloc[0]
        out_path = os.path.join(OUT_DIR, f"{str_row.str_id}.pdf")
        draw_certificate(out_path, str_row, party_row, spatial_row)

    print(f"Wrote {len(sample)} certificates to {OUT_DIR}")


if __name__ == "__main__":
    main()
